Create user roles
uwblueprint/child-witness-centre pull request #18
Opened 2024-02-09 01:15 UTC by itsjanevvu

## Notion Ticket Link

[Create User Roles](https://www.notion.so/uwblueprintexecs/Create-User-Roles-d9bc4346873b4c44964622df3b9563c5?pvs=4)

## Implementation Description
* Added volunteer, staff and admin roles to schema.

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

## Linting & Formatting
### Mac
```bash
docker exec -it CWC-backend /bin/bash -c "yarn fix"
docker exec -it CWC-frontend /bin/bash -c "yarn fix"
```

### Windows
```bash
docker exec -it CWC-backend bash -c "yarn fix"
docker exec -it CWC-frontend bash -c "yarn fix"
```

2024-02-09 01:26 UTC, achandrabalan approved these changes
LGTM! 
🔥 🧨

2024-02-09 05:42 UTC, carolynzhang18 commented
Nice work!! Two things:
1. The `role` prop of `AuthenticatedUser` in frontend/src/types/AuthTypes.ts should also be updated.
1.5. some of the unit tests also still have users with role "User", but I'm not sure if we need to update these cuz I don't thiiink we really ever test our code lol - maybe check with Owen on this?
(I did a search (ctrl-shift-F in VSCode) for `"User"` in our codebase to find these places)
2. Remember to run linter on the backend and frontend (command in README)! 🧹 

Otherwise it looks good! 😎

2024-02-09 05:44 UTC, carolynzhang18 requested changes
Nice work!! Two things:
1. The `role` prop of `AuthenticatedUser` in frontend/src/types/AuthTypes.ts should also be updated.
1.5. some of the unit tests also still have users with role "User", but I'm not sure if we need to update these cuz I don't thiiink we really ever test our code lol - maybe check with Owen on this?
(I did a search (ctrl-shift-F in VSCode) for `"User"` in our codebase to find these places)
2. Remember to run linter on the backend and frontend (command in README)! 🧹 

Otherwise it looks good! 😎

2024-02-12 02:20 UTC, carolynzhang18 approved these changes
Looks good!! 😻

2024-02-12 02:37 UTC, owen-sellner reviewed
I left one comment but after that it is ready to merge!!!

2024-02-12 02:37 UTC, owen-sellner commented on backend/models/user.model.ts
> +export default mongoose.model<User>("Volunteer", UserSchema);
This should be left as "User"

2024-02-12 02:51 UTC, merged