Adding user profile fields
uwblueprint/child-witness-centre pull request #25
Opened 2024-02-16 01:46 UTC by braydonwang

## Notion Ticket Link

[Add User Profile Fields](https://www.notion.so/uwblueprintexecs/Add-User-Profile-Fields-d7c41160b54641018752b4c1ad394f94#2fa82d9737fe451092a87bb492fc515f)

## Implementation Description
* Added additional fields to user schema
* Created custom scalar Date type with its resolver

## Steps to Test
1. Nothing at the moment, will need to wait for api endpoints

## What should reviewers focus on?
* Not very confident about the new resolver

## Screenshots (optional)

## Checklist
- [ ] My PR name is descriptive and in imperative tense
- [ ] My commit messages are descriptive and in imperative tense. My commits are atomic and trivial commits are squashed or fixup'd into non-trivial commits
- [ ] I have run the appropriate linter(s)
- [ ] I have requested a review from the PL, as well as other devs who have background knowledge on this PR or who will be building on top of this PR

## Linting & Formatting
### Mac
```bash
docker exec -it CWC-backend /bin/bash -c "yarn fix"
docker exec -it CWC-frontend /bin/bash -c "yarn fix"
```

### Windows
```bash
docker exec -it CWC-backend bash -c "yarn fix"
docker exec -it CWC-frontend bash -c "yarn fix"
```

2024-02-22 21:30 UTC, shencynthia commented on backend/models/user.model.ts
> +    enum: ["Remote", "Hybrid", "In Person"],
In the types file, for the Location Type enum field you have "InPerson" (no space) v.s "In Person" here.

2024-02-22 21:49 UTC, shencynthia requested changes
Just some small changes for consistency and also a nit: use imperative tense for commits + PR (e.g. Add rather than Adding).

Otherwise, looks good!!

2024-02-22 21:49 UTC, shencynthia commented on backend/models/user.model.ts
> +    enum: ["Remote", "Hybrid", "In Person"],
In the enum in userType you have "InPerson" and here its "In Person".

2024-02-22 21:49 UTC, shencynthia commented on backend/types.ts
> +export type LocationType = "Remote" | "Hybrid" | "In Person";
Same thing here, "InPerson" v.s "In Person"

2024-02-22 21:49 UTC, shencynthia commented on backend/types.ts
> +  headshot?: string;
In our Data Model we have headshot as non-optional.

2024-03-11 02:02 UTC, shencynthia approved these changes
LGTM! 👍👍👍

2024-03-12 04:16 UTC, carolynzhang18 commented on backend/models/user.model.ts
> +  },
Same comment as before here: these probably shouldn't be `required` - the current signup functionality will break :(

2024-03-19 02:46 UTC, owen-sellner approved these changes

2024-03-19 02:52 UTC, merged